### ISSUE TITLE
Please automate updating of the docs.

### ISSUE THREAD

**Issue by bcsgh** [open-source-parsers/jsoncpp-docs#2]
Right now the docs are more than 3 years behind:
1.8.3 (2017) https://github.com/open-source-parsers/jsoncpp-docs/blob/gh-pages/doxygen/index.html#L141
1.9.4 (2020) https://github.com/open-source-parsers/jsoncpp/blob/master/include/json/version.h#L12

It seems that reliance on manual updates to this repo is working. There are a number of turn-key CI solution that should be able to automate running the steps defined here: https://github.com/open-source-parsers/jsoncpp-docs#build-and-deploy any time master gets updated.

If you want to get fancy, you could do that for more than just master (pushing update generated from `$BRANCH` in .../jsoncpp to `$BRANCH` in .../jsoncpp-docs, mirroring tags, etc.).

**Comment by cdunn2001** [comment]
You're right. It should be automated. That's a good idea. Todo.

For now, the docs are updated to 1.9.4.

**Comment by bcsgh** [comment]
Thanks for updating the docs! :-) ... but:

What? You are saying you haven't done the thing I was suggesting, but plan to, and then *close* the issue? Isn't the point of an issue tracker to keep track of exactly this kind of thing until it's finished? [Note the request wasn't to update the docs once but rather to automate updating the docs.]

Or are you saying that this should be an issue on the other repo? (In which case I think the normal convention is to create an issue there and link it from here.)

**Comment by cdunn2001** [comment]
The docs were way out of date. Closed issue for that, the user-facing part.

The API rarely changes, so we're not too worried about it. An automatic solution would be interesting, but where? Travis-CI? (I'd rather wait for Travis-CI to stabilize. They are moving travis-ci.org to travis-ci.com.) Elsewhere? It requires pushing to another repo, and I've never set up a CI job that way before. Suggestions? Feel free to continue this thread here.

**Comment by bcsgh** [comment]
> The docs were way out of date. Closed issue for that, the user-facing part.

I figured that. I also specifically chose to not file an issue for that bit figuring it would happen regardless. ;-)
 
> The API rarely changes, so we're not too worried about it. An automatic solution would be interesting, but where? Travis-CI? (I'd rather wait for Travis-CI to stabilize. They are moving travis-ci.org to travis-ci.com.) Elsewhere?

I've never used Travis so I have no opinion on what automation tool to use.

> It requires pushing to another repo, and I've never set up a CI job that way before. Suggestions? Feel free to continue this thread here.

One option would be to have the jsoncpp repo be a git sub module of the jsoncpp-docs repo. Then the docs CI could sync that down, run the docs build and commit whatever changes (if any) come out of that. Or the CI could just `git clone` into a scratch directory?

The down side would be that I suspect triggering the CI based off a different repo being updated would be more complex. But as you pointed out, the API doesn't change much so doing that weekly(?) would likely be rather adequate.

**Comment by cdunn2001** [comment]
A submodule? That's not a bad idea.
